name: icl_ebm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - black
  - charset-normalizer
  - h5py
  - matplotlib
  - lightning
  - numpy
  - pandas
  - pytorch-gpu
  - pytorch-cuda=11.7
  - scipy
  - scikit-learn
  - scikit-image
  - seaborn
  - torchvision
  - wandb